create table apis (
    apis_id int8 generated by default as identity,
    developer_id int8,
    name varchar(255),
    quota int8 default 0,
    raw_type varchar(255) default 'JSON',
    routing_url varchar(255),
    status varchar(255) default 'PENDING',
    swagger_content TEXT default '{}',
    web_server_url varchar(255),
    white_list text[] default '{}',
    primary key (apis_id)
);

create table key (
    key_id int8 generated by default as identity,
    created_date date,
    expiration_date date,
    key_value varchar(32),
    primary key (key_id)
);

create table member (
    member_id int8 generated by default as identity,
    created_time timestamp,
    deleted_time timestamp,
    email varchar(30),
    key_id int8,
    password varchar(20) not null,
    role varchar(20) not null,
    primary key (member_id)
);

create table subscription (
    subscription_id int8 generated by default as identity,
    address varchar(255),
    apis_id int8 not null,
    content varchar(255),
    key_id int8,
    member_id int8 not null,
    status varchar(255),
    subscription_time timestamp,
    primary key (subscription_id)
);

alter table if exists key 
    add constraint UK_88ikfa3pgc58i36u3sey2g8cs unique (key_value);

alter table if exists member 
    add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email);

alter table if exists member 
    add constraint UK_1f7w463tut7m86ckqsdct9sul unique (key_id);

INSERT INTO key (created_date, expiration_date, key_value) values
    (CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', 'ait3Sf8mbTS2AZ0bKrB7EOt2fBZKAc4w');
INSERT INTO key (created_date, expiration_date, key_value) values
    (CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', 'berkljglkdfgjklfdkjgEOt2wehfskdf');
INSERT INTO key (created_date, expiration_date, key_value) values
    (CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', 'cerjgidfgjkeriudnfxcjkvlkdjlgdfj');

INSERT INTO member (email, password, created_time, role, key_id) values
    ('admin', 'admin', now() ,'ADMIN', 1);
INSERT INTO member (email, password, created_time, role, key_id) values
    ('developer', 'developer', now(), 'DEVELOPER', 2);
INSERT INTO member (email, password, created_time, role, key_id) values
    ('user', 'user', now(), 'USER', 3);
